# Configuration for golangci-lint
# Many of these issues are pre-existing in the upstream code
# TODO: Fix these properly and contribute upstream

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Don't check for unchecked errors in test files
    exclude-functions:
      - (*encoding/json.Encoder).Encode
      - (io.Closer).Close

issues:
  # Exclude pre-existing issues in upstream code
  # These should be fixed and contributed upstream
  exclude-rules:
    # Exclude errcheck issues in specific files (pre-existing upstream)
    - path: stores/github/github.go
      linters:
        - errcheck
    - path: internal/metrics/metrics.go
      linters:
        - errcheck
    - path: internal/queue/redis_test.go
      linters:
        - errcheck
    # Exclude all notifications files (pre-existing upstream issues)
    - path: internal/notifications/
      linters:
        - errcheck
    - path: internal/sync/done.go
      linters:
        - errcheck
    - path: internal/sync/filters.go
      linters:
        - errcheck
    - path: internal/sync/operator.go
      linters:
        - errcheck
    - path: internal/server/server.go
      linters:
        - errcheck
    # Exclude unused function warnings (pre-existing upstream)
    - path: stores/vault/vault.go
      linters:
        - unused
    - path: stores/gcp/gcp.go
      linters:
        - unused
    - path: internal/sync/utils.go
      linters:
        - unused
    # Exclude ineffassign (pre-existing upstream)
    - path: internal/config/config.go
      linters:
        - ineffassign
